version: "3.7"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.8.1
    restart: always
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      # ELASTIC_PASSWORD: "ISR_Spotlight"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    container_name: kibana
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elk

networks:
  elk:
